AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 24

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 120
